# Generated by Django 5.0.7 on 2024-07-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulettech', '0003_token_user_delete_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
