# Generated by Django 5.0.7 on 2024-07-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulettech', '0004_account_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
